name: createDockerImage

on:
  workflow_dispatch:
    inputs:
      running_branch:
        description: Which branch to checkout from
        required: false
        default: master 
jobs:

  createDockerImage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        clean: 'false'
        ref: ${{ github.event.inputs.running_branch }}
        
    - name: Docker build
      run: ls -la
    - name: Docker Push
      run: ls -la
